import type { E_Environment } from '@cyberskill/shared/typescript';

export interface I_Environment {
    NODE_ENV: E_Environment.DEVELOPMENT | E_Environment.PRODUCTION;
    NODE_ENV_MODE: E_Environment;
    IS_DEV: boolean;
    IS_STAG: boolean;
    IS_PROD: boolean;
    PORT: number;
    BASE_ENDPOINT: string;
    STATIC_FOLDER: string;
    BODY_PARSER_LIMIT: string;
    SESSION_NAME: string;
    SESSION_SECRET: string;
    MONGO_HOST: string;
    MONGO_PORT: number;
    MONGO_NAME: string;
    MONGO_USERNAME: string;
    MONGO_PASSWORD: string;
    MONGO_URI: string;
    MONGO_BACKUP_FOLDER: string;
    CORS_WHITELIST: string[];
    ENDPOINT_WS: string;
    ENDPOINT_GRAPHQL: string;
    ENDPOINT_RESTAPI: string;
    JWT_SECRET: string;
    IPINFO_TOKEN: string;
    UPLOAD_FOLDER: string;
    REDIS_HOST: string;
    REDIS_PORT: number;
    REDIS_PASSWORD: string;
    FROM_EMAIL_ADDRESS: string;
    AWS_ACCESS_KEY_ID: string;
    AWS_SECRET_ACCESS_KEY: string;
    AWS_SES_REGION: string;
    AWS_REKOGNITION_REGION: string;
    BUNNY_CDN_HOSTNAME: string;
    BUNNY_STORAGE_ZONE_NAME: string;
    BUNNY_STORAGE_API_KEY: string;
    BUNNY_STREAM_HOST_NAME: string;
    BUNNY_STREAM_LIBRARY_ID: string;
    BUNNY_STREAM_API_KEY: string;
}
